# Run rustfmt with this config (it should be picked up automatically).
version = "Two"
use_small_heuristics = "Max"
max_width = 120
struct_lit_width = 60
chain_width = 80
single_line_if_else_max_width = 60
single_line_let_else_max_width = 60

merge_derives = true
reorder_imports = true
# 格式化注释代码块：Unstable
format_code_in_doc_comments = true


# 彩色输出：Unstable
color = "Auto"
ignore = ["tests"]
